import type { Dict } from "./es";

// Traducció al català. Les xifres marcades com a "EJEMPLO" a es.ts també són il·lustratives aquí.
export const ca: Dict = {
  meta: {
    title: "Lateral Zinkin — Màrqueting i comunicació per a marques amb història",
    description:
      "Consultora boutique de màrqueting i comunicació a Madrid des del 2007. Estratègia, marca i comunicació per a editorials, institucions culturals, despatxos professionals i turisme.",
  },
  nav: {
    services: "Serveis",
    sectors: "Sectors",
    cases: "Casos",
    about: "Nacho",
    test: "Test",
    contact: "Contacte",
    cta: "Reserva una sessió",
    menu: "Menú",
    close: "Tancar",
    language: "Idioma",
  },
  common: {
    bookCta: "Reserva una sessió estratègica",
    testCta: "Fes el test de visibilitat",
    readMore: "Veure'n més",
    seeAll: "Veure'ls tots",
    backHome: "Tornar a l'inici",
    free: "30 min · Gratis · Sense compromís",
    skip: "Salta al contingut",
  },
  hero: {
    eyebrow: "Consultora boutique · Madrid · Des del 2007",
    titleA: "La teva marca té",
    titleB: "una història.",
    titleC: "L'expliquem des d'un",
    titleEm: "angle",
    titleD: "que ningú més veu.",
    sub: "Estratègia, marca i comunicació per a editorials, institucions culturals, despatxos professionals i marques de turisme que no volen assemblar-se a ningú.",
    primary: "Reserva una sessió estratègica",
    secondary: "Fes el test (3 min)",
    trust: "Han confiat en nosaltres",
    scroll: "Llisca",
  },
  stats: [
    { value: "2007", label: "any en què vam començar a mirar de costat" },
    { value: "50+", label: "marques acompanyades" },
    { value: "3", label: "sectors on som especialistes" },
    { value: "9/10", label: "clients repeteixen o ens recomanen" },
  ],
  lateral: {
    kicker: "El mètode",
    title: "No veiem res de nou. Veiem diferent el que tothom ha vist.",
    intro:
      "El pensament lateral consisteix a resoldre un problema des d'un angle que ningú havia provat. No és màgia ni una ocurrència: és mètode. I és el que fem amb cada marca.",
    chapters: [
      {
        name: "Dick Fosbury",
        year: "Mèxic, 1968",
        before: "Tothom saltava de cara.",
        after: "Ell va saltar d'esquena.",
        lesson: "Or olímpic. Avui tothom salta com ell.",
        img: "/img/fosbury.jpg",
      },
      {
        name: "Johan Cruyff",
        year: "Amsterdam, 1971",
        before: "Cada jugador tenia la seva posició.",
        after: "Ell les va jugar totes.",
        lesson: "Va inventar una manera d'entendre el joc que encara s'ensenya.",
        img: "/img/cruyff.jpg",
      },
      {
        name: "Jimi Hendrix",
        year: "Woodstock, 1969",
        before: "La guitarra es tocava així.",
        after: "Ell li va donar la volta.",
        lesson: "Esquerrà amb una guitarra de dretà. Va canviar el so del rock.",
        img: "/img/hendrix.jpg",
      },
    ],
    closingA: "El teu sector també té la seva manera “correcta” de fer les coses.",
    closingB: "Nosaltres busquem la teva.",
  },
  sectors: {
    kicker: "Sectors",
    title: "Especialistes en marques on la confiança ho és tot.",
    sub: "Treballem on el client no compra un producte, sinó una promesa: una història, un criteri, una experiència.",
    cta: "Com treballem a",
    items: [
      {
        slug: "cultura-editorial",
        num: "01",
        title: "Cultura i editorial",
        short: "Editorials, autors, museus, escoles i institucions culturals.",
        heroTitle: "Que allò que mereix ser llegit, vist i viscut trobi el seu públic.",
        heroSub:
          "Llançaments editorials, marca d'autor, comunicació d'institucions i projectes culturals. Amb criteri, sense estridències i amb resultats mesurables.",
        pains: [
          "Publiques bons llibres o programes bones activitats, però no arriben a qui haurien d'arribar.",
          "Cada llançament comença de zero i depèn de la sort amb la premsa.",
          "Les teves xarxes informen, però no construeixen comunitat.",
          "Et costa explicar per què la teva proposta és diferent de la dels grans.",
        ],
        services: [
          "Estratègia de llançament de llibres i col·leccions",
          "Marca personal d'autors",
          "Comunicació d'exposicions, festivals i programes",
          "Xarxes socials amb criteri editorial",
          "Newsletter i comunitat lectora",
          "Captació d'alumnes per a escoles",
        ],
        clients: ["Editorial Planeta", "Lonely Planet", "Museo Thyssen-Bornemisza", "Escuela de Escritores", "Sociedad Geográfica Española"],
        faq: [
          {
            q: "Treballeu amb autors individuals?",
            a: "Sí. Ajudem autors emergents i consolidats a construir una marca personal coherent, que vengui llibres sense trair la veu de l'autor.",
          },
          {
            q: "Feu premsa?",
            a: "Dissenyem l'estratègia de comunicació completa i coordinem la relació amb mitjans i prescriptors quan el projecte ho requereix.",
          },
          {
            q: "Amb quanta antelació cal començar un llançament?",
            a: "L'ideal és entre tres i sis mesos abans de la data de publicació o inauguració. Amb menys temps també es pot, però es renuncia a crear expectació.",
          },
        ],
      },
      {
        slug: "despachos-profesionales",
        num: "02",
        title: "Despatxos i serveis professionals",
        short: "Advocats, consultores, assessories i firmes de serveis.",
        heroTitle: "Que t'escullin pel que saps fer, no pel que cobres.",
        heroSub:
          "Màrqueting jurídic i de serveis professionals: posicionament, marca i captació de clients per a despatxos que volen créixer sense perdre prestigi.",
        pains: [
          "Gairebé tots els teus clients arriben per recomanació, i això no escala.",
          "La teva web s'assembla a la de qualsevol altre despatx.",
          "Competeixes per preu perquè el client no veu la diferència.",
          "Els socis no tenen temps per comunicar el que saben.",
        ],
        services: [
          "Posicionament i especialització del despatx",
          "Marca, naming i identitat corporativa",
          "Web orientada a captar consultes",
          "Marca personal dels socis a LinkedIn",
          "Contingut expert i SEO local",
          "Pla de màrqueting per a firmes en creixement",
        ],
        clients: ["Bennet & Rey Abogados", "Valentín Gamazo Abogados", "Camacho & Aparicio", "LC Rodrigo Abogados", "FTr Consultants", "Sergat"],
        faq: [
          {
            q: "El màrqueting és compatible amb la deontologia de l'advocacia?",
            a: "Totalment. Fa anys que treballem amb despatxos i en coneixem els límits: comuniquem coneixement i confiança, mai promeses de resultat.",
          },
          {
            q: "Treballeu amb despatxos petits?",
            a: "Sí, i és on més es nota l'impacte. Molts dels nostres clients van començar amb un o dos socis.",
          },
          {
            q: "Quant de temps triga a notar-se?",
            a: "El posicionament i la marca es noten des del primer dia en com et perceben. La captació constant sol consolidar-se entre els sis i els dotze mesos.",
          },
        ],
      },
      {
        slug: "turismo-experiencias",
        num: "03",
        title: "Turisme i experiències",
        short: "Agències de viatges, destinacions, escoles d'idiomes i experiències culturals.",
        heroTitle: "Que viatgin amb tu perquè ningú més explica el viatge com tu.",
        heroSub:
          "Estratègia digital, marca i comunicació per a agències boutique, destinacions i experiències culturals que competeixen amb gegants i cercadors.",
        pains: [
          "Els grans portals i cercadors es queden el teu client.",
          "La teva proposta és única, però a internet sembla una més.",
          "Depens de temporades i de campanyes d'última hora.",
          "No tens una comunitat pròpia de viatgers fidels.",
        ],
        services: [
          "Estratègia digital i reposicionament d'agència",
          "Storytelling de destinacions i experiències",
          "Contingut i xarxes per a viatgers culturals",
          "Newsletter i comunitat pròpia",
          "Comunicació de destinacions i institucions turístiques",
          "Llançament de noves rutes i productes",
        ],
        clients: ["Lonely Planet", "Viajes Nieva", "Viajes Sakai", "Turismo Castilla-La Mancha", "ComeMai", "Studiainitalia"],
        faq: [
          {
            q: "Treballeu amb destinacions i institucions públiques?",
            a: "Sí, hem treballat amb destinacions i centres d'interpretació turística, a més d'agències privades.",
          },
          {
            q: "Ens podeu ajudar a dependre menys dels grans portals?",
            a: "És un dels nostres objectius habituals: construir marca, comunitat i canals propis perquè el viatger et busqui a tu.",
          },
          {
            q: "Gestioneu campanyes de publicitat?",
            a: "Sí, les integrem a l'estratègia quan tenen sentit, sempre amb objectius i mètriques clares.",
          },
        ],
      },
    ],
  },
  services: {
    kicker: "Serveis",
    title: "Poques coses. Molt ben fetes.",
    sub: "Som el teu cap estratègic quan necessites claredat, i les teves mans quan tens claredat però no temps.",
    items: [
      {
        num: "01",
        title: "Estratègia i posicionament",
        desc: "Analitzem la teva marca, el teu entorn i la teva competència per trobar el lloc que només tu pots ocupar. I ho convertim en un pla.",
        bullets: ["Auditoria de màrqueting i comunicació", "Anàlisi de l'entorn i la competència", "Pla de màrqueting i pla estratègic", "Reposicionament de marca"],
      },
      {
        num: "02",
        title: "Marca i identitat",
        desc: "Creem la imatge i la veu del teu projecte a partir de les teves idees i valors: des del nom fins a l'últim suport.",
        bullets: ["Naming", "Logotip i identitat corporativa", "Identitat verbal i narrativa de marca", "Manual de marca"],
      },
      {
        num: "03",
        title: "Web, continguts i xarxes",
        desc: "Ens encanta comunicar i explicar històries. Construïm presència digital que atrau les persones adequades i les converteix en clients.",
        bullets: ["Disseny i desenvolupament web", "Estratègia de xarxes socials i community management", "Social Ads", "Monitoratge i reputació online"],
      },
      {
        num: "04",
        title: "Acompanyament estratègic",
        desc: "El teu director de màrqueting extern: proper, professional i diferent. Per a marques que volen un soci, no un proveïdor.",
        bullets: ["Direcció de màrqueting externa", "Coaching a fundadors i emprenedors", "Marca personal", "Formació d'equips"],
      },
    ],
  },
  method: {
    kicker: "Com treballem",
    title: "Del briefing al resultat, sense dreceres.",
    steps: [
      { title: "Escoltem", desc: "Reivindiquem el briefing. Entenem el que ens dius i el que vols dir però no dius." },
      { title: "Mirem de costat", desc: "Estudiem el teu mercat i la teva competència fins a trobar l'angle que ningú està fent servir." },
      { title: "Construïm", desc: "Estratègia, marca i comunicació amb un pla clar, mesurable i realista." },
      { title: "Acompanyem", desc: "Executem, mesurem i ajustem amb tu. L'acompanyament forma part de la promesa." },
    ],
  },
  cases: {
    kicker: "Casos",
    title: "Marques que ja es veuen diferent.",
    sub: "Alguns projectes amb què hem treballat. En els casos confidencials mantenim l'anonimat del client.",
    confidential: "Cas confidencial",
    challenge: "El repte",
    angle: "L'angle",
    result: "El resultat",
    items: [
      {
        sector: "cultura-editorial",
        client: "Editorial Planeta",
        anonymous: false,
        title: "Més presència de marca en un negoci que canvia cada dia",
        challenge: "Un sector amb canvis constants, llançaments continus i la necessitat d'adaptar-se a la improvisació.",
        angle: "Anàlisi contínua de cada acció i una estratègia de xarxes flexible, capaç de reaccionar sense perdre coherència.",
        result: "Millora de la presència de la marca i un augment notable de seguidors.",
        metrics: [],
      },
      {
        sector: "cultura-editorial",
        client: "Segell editorial independent · Barcelona",
        anonymous: true,
        title: "Una novel·la debut que va exhaurir tres edicions",
        challenge: "Autora desconeguda, pressupost limitat i una data de llançament competint amb les grans novetats de tardor.",
        angle: "En lloc de vendre el llibre, vam vendre la conversa: un club de lectura previ amb llibreters i lectors prescriptors.",
        result: "El llibre va arribar a les llibreries amb llista d'espera i la premsa va venir darrere.",
        metrics: [
          { value: "3", label: "reedicions en 5 mesos" },
          { value: "+186%", label: "prevendes vs. llançament anterior" },
          { value: "41", label: "aparicions en mitjans" },
        ],
      },
      {
        sector: "despachos-profesionales",
        client: "Bennet & Rey Abogados",
        anonymous: false,
        title: "Posicionar un despatx des del primer dia",
        challenge: "Un despatx que començava i no sabia com posicionar-se al mercat ni com arribar als seus clients.",
        angle: "Escolta profunda del projecte per convertir la seva diferència en eines de màrqueting concretes.",
        result: "Idees i eines que es van convertir en la base del seu màrqueting.",
        metrics: [],
      },
      {
        sector: "despachos-profesionales",
        client: "Despatx boutique de dret mercantil · Madrid",
        anonymous: true,
        title: "De dependre del boca-orella a omplir l'agenda",
        challenge: "Quatre socis brillants, una web genèrica i el 90% dels clients arribant per recomanació.",
        angle: "Vam deixar de parlar de “serveis integrals” i vam posicionar el despatx com l'especialista en operacions d'empresa familiar.",
        result: "Consultes més qualificades, millors honoraris i els socis com a referents del seu nínxol.",
        metrics: [
          { value: "4 → 17", label: "consultes qualificades al mes" },
          { value: "+32%", label: "honorari mitjà per assumpte" },
          { value: "9", label: "mesos per aconseguir-ho" },
        ],
      },
      {
        sector: "turismo-experiencias",
        client: "Viajes Nieva",
        anonymous: false,
        title: "Repensar una agència davant la cruïlla digital",
        challenge: "Una agència en un mercat turístic canviant, davant noves formes de cerca i recomanació de viatges.",
        angle: "Visió estratègica per avançar-se als esdeveniments i redefinir el paper de l'agència boutique.",
        result: "Decisions clau per al seu desenvolupament com a empresa.",
        metrics: [],
      },
      {
        sector: "turismo-experiencias",
        client: "Agència de viatges culturals · Madrid",
        anonymous: true,
        title: "Viatgers que reserven sense passar pels portals",
        challenge: "Competia en preu amb plataformes gegants amb un producte que no s'hi assemblava gens.",
        angle: "Vam convertir els guies en protagonistes i vam llançar una newsletter amb relats de cada ruta.",
        result: "Una comunitat pròpia que reserva directament i paga per l'experiència, no pel preu.",
        metrics: [
          { value: "38%", label: "reserves des de la newsletter" },
          { value: "+24%", label: "tiquet mitjà per viatger" },
          { value: "6.200", label: "subscriptors en un any" },
        ],
      },
    ],
  },
  testimonials: {
    kicker: "Opinions",
    title: "El que diuen els qui ja han treballat amb nosaltres.",
    items: [
      {
        quote:
          "En un negoci com el nostre, en què hi ha canvis constantment, és molt important comptar amb una persona com Nacho Latorre capaç d'adaptar-se a les improvisacions. La seva anàlisi i el seu coneixement de les xarxes socials ens han permès millorar la presència de la marca i augmentar notablement els seguidors.",
        name: "Laura Franch",
        role: "Directora de Comunicació",
        company: "Editorial Planeta",
      },
      {
        quote:
          "Als escriptors ens perden els detalls, la visió microscòpica. Seguint amb el símil literari, Nacho Latorre seria un expert a donar versemblança al teu relat, en aquest cas, al teu negoci. Les seves anàlisis i consells han estat una ajuda fonamental per a nosaltres.",
        name: "Germán Solís",
        role: "Sotsdirector",
        company: "Escuela de Escritores",
      },
      {
        quote:
          "La seva visió estratègica, la seva capacitat d'avançar-se als esdeveniments i els seus profunds coneixements del màrqueting i el món digital ens van ajudar a prendre decisions que han estat clau per al nostre desenvolupament com a empresa.",
        name: "Paloma Nieva",
        role: "Sòcia fundadora",
        company: "Viajes Sakai i Viajes Nieva",
      },
      {
        quote:
          "Una de les millors idees que vam tenir va ser contractar Lateral Zinkin. Començàvem el nostre negoci i no sabíem com posicionar-nos al mercat. Les idees del Nacho s'han convertit en valuoses eines de màrqueting per a la nostra empresa.",
        name: "Margaret Hauschild",
        role: "Sòcia directora",
        company: "Bennet & Rey Lawyers",
      },
      {
        quote:
          "Nacho Latorre va fer amb el seu equip una molt bona feina de reposicionament de la nostra marca. Això ha fet que hàgim augmentat les vendes i millorat la nostra imatge de marca, que era el que buscàvem.",
        name: "Alberto Gutiérrez",
        role: "Director general",
        company: "ElPeriódicoDeTuDía",
      },
      {
        quote:
          "No només hem millorat les vendes i la competitivitat, sinó que en els moments més crucials, les seves paraules de suport i d'anàlisi externa han estat clau per seguir i millorar el nostre projecte.",
        name: "Francesca Murru",
        role: "Sòcia fundadora",
        company: "ComeMai",
      },
      {
        quote:
          "Un partner eficient i eficaç que millora la visió del teu negoci, acompanya el creixement de la teva empresa i sempre té un assessorament intel·ligent disponible.",
        name: "Nina Morillas",
        role: "Fundadora i directora",
        company: "Pinkus i María Wolff",
      },
      {
        quote:
          "El tracte del Nacho va ser molt proper, pròxim i professional en tot moment. La seva anàlisi de la nostra situació en màrqueting i comunicació va ser molt encertada.",
        name: "Antonio Lence",
        role: "Director general",
        company: "Viena Capellanes",
      },
    ],
    translated: "Traducció de l'original en castellà.",
  },
  founder: {
    kicker: "Qui hi ha al darrere",
    name: "Nacho Latorre Tambo",
    role: "Soci fundador · Consultor · Professor de màrqueting",
    teaser:
      "Des del 2007, el Nacho ha acompanyat editorials, museus, despatxos i agències de viatges a trobar el seu angle. Al darrere, un grup flexible de professionals amb dècades d'experiència.",
    bio: [
      "Llicenciat en Dret i diplomat en Ciències Empresarials per ICADE, amb un Màster en Direcció Comercial i Màrqueting, el Nacho va fundar Lateral Zinkin el 2007 amb una idea senzilla: que el màrqueting extern podia ser proper, professional i diferent.",
      "És expert en màrqueting de serveis i despatxos professionals, màrqueting per a emprenedors, xarxes socials i transformació digital. Ha col·laborat en la gestió de xarxes de Lonely Planet Espanya i ha treballat amb marques com Editorial Planeta, el Museo Thyssen-Bornemisza o Escuela de Escritores.",
      "Compagina la consultoria amb la docència com a professor de màrqueting a IMF Smart Education, on forma els professionals que avui dirigeixen el màrqueting de moltes empreses.",
    ],
    credentials: [
      "Dret i Empresarials · ICADE",
      "Màster en Direcció Comercial i Màrqueting",
      "Professor de màrqueting · IMF Smart Education",
      "Expert en màrqueting jurídic i de serveis",
    ],
    quote: "El valor d'una consultora és generar estratègies i creativitat que arribin amb eficàcia als clients dels nostres clients.",
    photoAlt: "Retrat de Nacho Latorre Tambo",
    yearsLabel: "anys",
    cta: "Coneix el Nacho",
    team: "Un equip flexible",
    teamDesc:
      "Segons cada projecte hi sumem dissenyadors, desenvolupadors, redactors i especialistes en mitjans amb dècades d'experiència. Sempre amb el Nacho al capdavant: res de comptes que passen de júnior en júnior.",
  },
  quizTeaser: {
    kicker: "Test gratuït · 3 minuts",
    title: "Com de visible és la teva marca?",
    sub: "Vuit preguntes per mesurar la claredat, la diferenciació, la visibilitat i la conversió de la teva marca. Rebràs un diagnòstic personalitzat amb recomanacions concretes.",
    cta: "Començar el test",
    bullets: ["Claredat", "Diferenciació", "Visibilitat", "Conversió"],
  },
  newsletter: {
    kicker: "Newsletter",
    title: "Idees laterals, un cop al mes.",
    sub: "Casos, eines i reflexions sobre màrqueting per a marques amb història. Sense soroll. Et pots donar de baixa quan vulguis.",
    cta: "Subscriure'm a Substack",
  },
  finalCta: {
    title: "Parlem de la teva marca?",
    sub: "Una sessió estratègica de 30 minuts. Ens expliques el teu projecte, et donem una primera lectura honesta i decideixes si continuem. Sense compromís.",
    primary: "Reserva la teva sessió",
    secondary: "o escriu-nos per WhatsApp",
  },
  contact: {
    kicker: "Contacte",
    title: "Parlem de la teva marca.",
    sub: "Reserva directament una sessió estratègica o explica'ns el teu projecte i et respondrem en menys de 24 hores laborables.",
    bookingTitle: "Reserva la teva sessió estratègica",
    bookingSub: "30 minuts per videotrucada. Gratis i sense compromís.",
    bookingPending: "Molt aviat podràs reservar aquí directament. Mentrestant, deixa'ns les teves dades i et proposarem horari.",
    formTitle: "Explica'ns el teu projecte",
    form: {
      name: "Nom",
      email: "Correu electrònic",
      company: "Empresa o projecte",
      phone: "Telèfon (opcional)",
      sector: "Sector",
      sectorOptions: ["Cultura i editorial", "Despatx o serveis professionals", "Turisme i experiències", "Altres"],
      budget: "Inversió mensual aproximada",
      budgetOptions: ["Encara no ho sé", "Menys de 1.000 €", "1.000 – 3.000 €", "3.000 – 6.000 €", "Més de 6.000 €"],
      message: "Què vols aconseguir?",
      messagePlaceholder: "Explica'ns en què estàs treballant i què t'agradaria aconseguir.",
      consentA: "He llegit i accepto la",
      consentLink: "política de privacitat",
      submit: "Enviar",
      sending: "Enviant…",
      success: "Rebut! T'escriurem en menys de 24 hores laborables.",
      error: "No hem pogut enviar el formulari. Escriu-nos directament a",
      required: "Revisa els camps obligatoris.",
    },
    details: {
      phoneLabel: "Telèfon",
      whatsappLabel: "WhatsApp",
      whatsappText: "Escriu-nos per WhatsApp",
      emailLabel: "Correu",
      addressLabel: "Estudi",
    },
  },
  quiz: {
    title: "Test de visibilitat de marca",
    intro: "Respon amb sinceritat. No hi ha respostes bones ni dolentes: només un punt de partida.",
    start: "Començar",
    step: "Pregunta",
    of: "de",
    back: "Anterior",
    dims: {
      clarity: "Claredat",
      difference: "Diferenciació",
      visibility: "Visibilitat",
      conversion: "Conversió",
    },
    questions: [
      {
        dim: "clarity",
        q: "Si algú entra a la teva web per primera vegada, entén en cinc segons què fas i per a qui?",
        options: ["No tinc web o està desactualitzada", "Crec que no del tot", "Més o menys", "Sí, sense cap dubte"],
      },
      {
        dim: "clarity",
        q: "Tens definit per escrit el teu posicionament i el teu client ideal?",
        options: ["No", "El tinc al cap", "Sí, però no el fem servir", "Sí, i guia tot el que comuniquem"],
      },
      {
        dim: "difference",
        q: "Què et diferencia de la teva competència?",
        options: ["No ho tinc clar", "El preu", "La qualitat i el tracte proper", "Alguna cosa concreta que només fem nosaltres"],
      },
      {
        dim: "difference",
        q: "Si treus el logotip de la teva web i de la de la competència, es distingeixen?",
        options: ["Serien gairebé iguals", "S'assemblarien força", "Alguna cosa es nota", "Som inconfusibles"],
      },
      {
        dim: "visibility",
        q: "Com et troben la majoria dels teus nous clients?",
        options: ["Gairebé només pel boca-orella", "Xarxes socials de manera irregular", "Diverses fonts, sense pla", "Google, contingut, premsa i recomanació amb un pla"],
      },
      {
        dim: "visibility",
        q: "Amb quina freqüència publiques contingut amb criteri (articles, xarxes, newsletter)?",
        options: ["Gairebé mai", "Quan hi ha temps", "Cada mes", "Cada setmana, amb calendari"],
      },
      {
        dim: "conversion",
        q: "Quan algú interessat visita la teva web, què passa després?",
        options: ["Res, no hi ha una manera clara de contactar", "Un correu o un formulari genèric", "Un formulari i responem ràpid", "Un camí clar: reservar, descarregar o subscriure's"],
      },
      {
        dim: "conversion",
        q: "Saps quants contactes et arriben al mes i de quin canal venen?",
        options: ["Ni idea", "Una intuïció", "Aproximadament", "Sí, ho mesurem tot"],
      },
    ],
    gate: {
      title: "El teu diagnòstic està a punt.",
      sub: "Deixa'ns el teu correu per veure l'informe complet amb les teves puntuacions i recomanacions. També te l'enviarem per correu.",
      name: "Nom",
      email: "Correu electrònic",
      sector: "Sector",
      consent: "Accepto la política de privacitat i rebre el diagnòstic per correu.",
      submit: "Veure el meu diagnòstic",
      preview: "La teva puntuació global",
    },
    results: {
      title: "El teu diagnòstic",
      overall: "Puntuació global",
      tiers: [
        {
          min: 0,
          title: "Marca invisible",
          desc: "La teva marca té molt a explicar, però ara mateix el mercat no l'escolta. La bona notícia: és on més ràpid es noten els canvis.",
        },
        {
          min: 40,
          title: "Potencial adormit",
          desc: "Tens bases sòlides, però hi ha fuites importants entre el que ets i el que el mercat percep. Amb l'angle adequat, el salt pot ser gran.",
        },
        {
          min: 70,
          title: "A punt per enlairar-se",
          desc: "La teva marca està ben construïda. El següent nivell és afinar la diferenciació i escalar el que ja funciona.",
        },
      ],
      recsTitle: "Les nostres recomanacions",
      recs: {
        clarity: "Defineix per escrit per a qui ets i quin problema resols, i fes que la teva portada ho digui en una frase.",
        difference: "Busca el teu angle: allò que només tu pots dir. Si la teva competència podria signar el teu missatge, encara no l'has trobat.",
        visibility: "Construeix canals propis i constants: contingut expert, newsletter i relació amb prescriptors. El boca-orella no escala sol.",
        conversion: "Dissenya un camí clar per a cada visitant: reservar una trucada, descarregar alguna cosa útil o subscriure's. I mesura-ho.",
      },
      allGood: "Les teves quatre àrees estan en bona forma. Parlem de com escalar el que ja funciona.",
      nextTitle: "I ara què?",
      nextSub: "Revisem el teu diagnòstic amb tu en una sessió estratègica gratuïta de 30 minuts.",
      bookCta: "Reservar sessió",
      newsletterCta: "Rebre idees laterals",
      retake: "Repetir el test",
    },
  },
  footer: {
    claim: "Ideas & Marketing per a marques amb història.",
    rights: "Tots els drets reservats.",
    legal: { aviso: "Avís legal", privacidad: "Privacitat", cookies: "Galetes" },
    explore: "Explora",
    contact: "Contacte",
    follow: "Segueix-nos",
  },
  pages: {
    services: { title: "Serveis", sub: "Estratègia, marca i comunicació. Cap i mans." },
    sectors: { title: "Sectors" },
    cases: { title: "Casos", sub: "Projectes, reptes i resultats." },
    about: { title: "Nacho Latorre Tambo" },
    test: { title: "Test de visibilitat de marca", sub: "3 minuts. 8 preguntes. Un diagnòstic honest." },
    contact: { title: "Contacte" },
    legalNote: "Aquest text legal es facilita en castellà, que és la versió vinculant.",
  },
};
