import type { Dict } from "./es";

// English translation. Follow docs/seo/normas-contenido.md and docs/seo/voz-de-marca.md.
export const en: Dict = {
  // Títulos (sin la marca, se añade sola) y descripciones para Google. Normas: title 30–60 con marca, description 120–155.
  seo: {
    home: { title: "Boutique marketing consultancy in Madrid", description: "Strategy, branding and communication for publishers, law firms and tourism brands. A boutique marketing consultancy based in Madrid since 2007." },
    services: { title: "Marketing and communication consultancy", description: "Strategy, positioning, branding, web and social media for brands with a story. Outsourced marketing direction from Madrid, led by Nacho Latorre." },
    cases: { title: "Marketing and communication case studies", description: "Editorial Planeta, Bennet & Rey, Viajes Nieva and more: the challenge, the angle we found and the result of each marketing project we led." },
    about: { title: "Nacho Latorre Tambo, marketing consultant", description: "Founder of Lateral Zinkin and marketing lecturer at IMF. Since 2007 he has helped publishers, law firms and travel agencies find their angle." },
    test: { title: "Free brand visibility test in three minutes", description: "Eight questions, three minutes: measure your brand's clarity, differentiation, visibility and conversion. Free diagnosis with recommendations." },
    contact: { title: "Contact us: book a strategy session", description: "Book a free 30-minute strategy session or tell us about your project. We reply within 24 business hours from our studio in Madrid." },
    ideas: { title: "Marketing ideas for brands with a story", description: "Articles by Nacho Latorre on publishing, legal and travel marketing: real cases, our own data and the angle no one else is using." },
    sectors: {
      "cultura-editorial": { title: "Publishing and cultural marketing in Madrid", description: "Book launches, author branding and communication for museums and cultural institutions. We have worked with Planeta, Lonely Planet and the Thyssen." },
      "despachos-profesionales": { title: "Law firm marketing in Spain", description: "Positioning, branding and client acquisition for law firms and professional services firms that want to grow without losing prestige. Based in Madrid." },
      "turismo-experiencias": { title: "Marketing for travel agencies and tourism", description: "Digital strategy, branding and an owned community for boutique travel agencies, destinations and cultural experiences competing with big portals." },
    } as Record<string, { title: string; description: string }>,
  },
  nav: {
    services: "Services",
    sectors: "Sectors",
    cases: "Work",
    about: "Nacho",
    ideas: "Ideas",
    test: "Test",
    contact: "Contact",
    cta: "Book a session",
    menu: "Menu",
    close: "Close",
    language: "Language",
  },
  common: {
    bookCta: "Book a strategy session",
    testCta: "Take the visibility test",
    readMore: "Read more",
    seeAll: "See all",
    backHome: "Back to home",
    free: "30 min · Free · No strings attached",
    skip: "Skip to content",
  },
  hero: {
    eyebrow: "Boutique consultancy · Madrid · Since 2007",
    titleA: "Your brand has",
    titleB: "a story.",
    titleC: "We tell it from the",
    titleEm: "angle",
    titleD: "no one else sees.",
    sub: "Strategy, branding and communication for publishers, cultural institutions, professional firms and tourism brands that refuse to look like anyone else.",
    primary: "Book a strategy session",
    secondary: "Take the test (3 min)",
    trust: "Trusted by",
    scroll: "Scroll",
  },
  stats: [
    { value: "2007", label: "the year we started looking sideways" },
    { value: "50+", label: "brands supported" },
    { value: "3", label: "sectors where we specialise" },
    { value: "9/10", label: "clients come back or refer us" },
  ],
  lateral: {
    kicker: "The method",
    title: "We see nothing new. We see differently what everyone has seen.",
    intro:
      "Lateral thinking means solving a problem from an angle no one has tried. It isn't magic or a lucky idea: it's a method. And it's what we do with every brand.",
    chapters: [
      {
        name: "Dick Fosbury",
        year: "Mexico City, 1968",
        before: "Everyone jumped face first.",
        after: "He jumped backwards.",
        lesson: "Olympic gold. Today everyone jumps like him.",
        scene: "fosbury",
      },
      {
        name: "Johan Cruyff",
        year: "Dortmund, 1974",
        before: "The defender expected a cross.",
        after: "He turned around.",
        lesson: "The “Cruyff turn”. Today it’s taught at every football academy.",
        scene: "cruyff",
      },
      {
        name: "Jimi Hendrix",
        year: "Woodstock, 1969",
        before: "This is how a guitar was played.",
        after: "He turned it upside down.",
        lesson: "A left-hander on a right-handed guitar. He changed the sound of rock.",
        scene: "hendrix",
      },
    ],
    closingA: "Your sector also has its “right” way of doing things.",
    closingB: "We look for yours.",
  },
  sectors: {
    kicker: "Sectors",
    title: "Specialists in brands where trust is everything.",
    sub: "We work where clients don't buy a product but a promise: a story, a point of view, an experience.",
    cta: "See how we work in",
    items: [
      {
        slug: "cultura-editorial",
        num: "01",
        title: "Culture & publishing",
        short: "Publishers, authors, museums, schools and cultural institutions.",
        heroTitle: "So that what deserves to be read, seen and lived finds its audience.",
        heroSub:
          "Book launches, author branding, communication for institutions and cultural projects. With judgement, without noise, and with measurable results.",
        pains: [
          "You publish great books or run great programmes, but they don't reach the people they should.",
          "Every launch starts from scratch and depends on luck with the press.",
          "Your social media informs, but doesn't build community.",
          "It's hard to explain why your proposal is different from the big players.",
        ],
        services: [
          "Launch strategy for books and collections",
          "Author personal branding",
          "Communication for exhibitions, festivals and programmes",
          "Social media with editorial judgement",
          "Newsletter and reader community",
          "Student acquisition for schools",
        ],
        clients: ["Editorial Planeta", "Lonely Planet", "Museo Thyssen-Bornemisza", "Escuela de Escritores", "Sociedad Geográfica Española"],
        faq: [
          {
            q: "Do you work with individual authors?",
            a: "Yes. We help emerging and established authors build a coherent personal brand that sells books without betraying the author's voice.",
          },
          {
            q: "Do you handle press?",
            a: "We design the full communication strategy and coordinate relations with media and influencers when the project requires it.",
          },
          {
            q: "How far ahead should a launch start?",
            a: "Ideally three to six months before publication or opening. It can be done with less time, but you give up building anticipation.",
          },
        ],
      },
      {
        slug: "despachos-profesionales",
        num: "02",
        title: "Law & professional firms",
        short: "Law firms, consultancies, advisory and professional services.",
        heroTitle: "Get chosen for what you know, not for what you charge.",
        heroSub:
          "Legal and professional services marketing: positioning, branding and client acquisition for firms that want to grow without losing prestige.",
        pains: [
          "Almost all your clients come through referrals, and that doesn't scale.",
          "Your website looks like any other firm's.",
          "You compete on price because clients can't see the difference.",
          "Partners don't have time to share what they know.",
        ],
        services: [
          "Firm positioning and specialisation",
          "Branding, naming and corporate identity",
          "Websites built to generate enquiries",
          "Partner personal branding on LinkedIn",
          "Expert content and local SEO",
          "Marketing plan for growing firms",
        ],
        clients: ["Bennet & Rey Abogados", "Valentín Gamazo Abogados", "Camacho & Aparicio", "LC Rodrigo Abogados", "FTr Consultants", "Sergat"],
        faq: [
          {
            q: "Is marketing compatible with legal professional ethics?",
            a: "Completely. We have worked with law firms for years and know the limits: we communicate knowledge and trust, never promises of results.",
          },
          {
            q: "Do you work with small firms?",
            a: "Yes, and that's where the impact shows most. Many of our clients started with one or two partners.",
          },
          {
            q: "How long until we see results?",
            a: "Positioning and branding change how you're perceived from day one. Consistent client acquisition usually consolidates between six and twelve months.",
          },
        ],
      },
      {
        slug: "turismo-experiencias",
        num: "03",
        title: "Tourism & experiences",
        short: "Travel agencies, destinations, language schools and cultural experiences.",
        heroTitle: "People travel with you because no one else tells the journey like you.",
        heroSub:
          "Digital strategy, branding and communication for boutique agencies, destinations and cultural experiences competing against giants and search engines.",
        pains: [
          "Big portals and search engines take your customers.",
          "Your offer is unique, but online it looks like just another one.",
          "You depend on seasons and last-minute campaigns.",
          "You don't have your own community of loyal travellers.",
        ],
        services: [
          "Digital strategy and agency repositioning",
          "Storytelling for destinations and experiences",
          "Content and social media for cultural travellers",
          "Newsletter and owned community",
          "Communication for destinations and tourism bodies",
          "Launch of new routes and products",
        ],
        clients: ["Lonely Planet", "Viajes Nieva", "Viajes Sakai", "Turismo Castilla-La Mancha", "ComeMai", "Studiainitalia"],
        faq: [
          {
            q: "Do you work with destinations and public institutions?",
            a: "Yes, we have worked with destinations and tourist interpretation centres as well as private agencies.",
          },
          {
            q: "Can you help us depend less on big portals?",
            a: "It's one of our usual goals: building brand, community and owned channels so travellers look for you.",
          },
          {
            q: "Do you run advertising campaigns?",
            a: "Yes, we integrate them into the strategy when they make sense, always with clear goals and metrics.",
          },
        ],
      },
    ],
  },
  services: {
    kicker: "Services",
    title: "A few things. Done very well.",
    sub: "We are your strategic mind when you need clarity, and your hands when you have clarity but no time.",
    items: [
      {
        num: "01",
        title: "Strategy & positioning",
        desc: "We analyse your brand, market and competitors to find the place only you can own. Then we turn it into a plan.",
        bullets: ["Marketing and communication audit", "Market and competitor analysis", "Marketing plan and strategic plan", "Brand repositioning"],
      },
      {
        num: "02",
        title: "Brand & identity",
        desc: "We create your project's image and voice from your ideas and values: from the name to the very last touchpoint.",
        bullets: ["Naming", "Logo and corporate identity", "Verbal identity and brand narrative", "Brand guidelines"],
      },
      {
        num: "03",
        title: "Web, content & social",
        desc: "We love communicating and telling stories. We build a digital presence that attracts the right people and turns them into clients.",
        bullets: ["Web design and development", "Social media strategy and community management", "Social ads", "Monitoring and online reputation"],
      },
      {
        num: "04",
        title: "Strategic partnership",
        desc: "Your external marketing director: close, professional and different. For brands that want a partner, not a supplier.",
        bullets: ["Outsourced marketing direction", "Coaching for founders and entrepreneurs", "Personal branding", "Team training"],
      },
    ],
  },
  method: {
    kicker: "How we work",
    title: "From brief to results, no shortcuts.",
    steps: [
      { title: "We listen", desc: "We champion the brief. We understand what you say and what you mean but don't say." },
      { title: "We look sideways", desc: "We study your market and competitors until we find the angle no one is using." },
      { title: "We build", desc: "Strategy, brand and communication with a clear, measurable and realistic plan." },
      { title: "We stay with you", desc: "We execute, measure and adjust with you. Support is part of the promise." },
    ],
  },
  cases: {
    kicker: "Work",
    title: "Brands that already look different.",
    sub: "Some of the projects we've worked on. For confidential cases we keep the client anonymous.",
    confidential: "Confidential case",
    challenge: "The challenge",
    angle: "The angle",
    result: "The result",
    items: [
      {
        sector: "cultura-editorial",
        client: "Editorial Planeta",
        anonymous: false,
        title: "Stronger brand presence in a business that changes every day",
        challenge: "A sector with constant change, continuous launches and the need to adapt to improvisation.",
        angle: "Continuous analysis of every action and a flexible social strategy able to react without losing coherence.",
        result: "Improved brand presence and a notable increase in followers.",
        metrics: [],
      },
      {
        sector: "cultura-editorial",
        client: "Independent publisher · Barcelona",
        anonymous: true,
        title: "A debut novel that sold out three printings",
        challenge: "An unknown author, a limited budget and a release date competing with the big autumn titles.",
        angle: "Instead of selling the book, we sold the conversation: an early reading club with booksellers and influential readers.",
        result: "The book reached bookshops with a waiting list, and the press followed.",
        metrics: [
          { value: "3", label: "reprints in 5 months" },
          { value: "+186%", label: "pre-orders vs. previous launch" },
          { value: "41", label: "media mentions" },
        ],
      },
      {
        sector: "despachos-profesionales",
        client: "Bennet & Rey Abogados",
        anonymous: false,
        title: "Positioning a law firm from day one",
        challenge: "A new firm that didn't know how to position itself or reach its clients.",
        angle: "Deep listening to turn the firm's difference into concrete marketing tools.",
        result: "Ideas and tools that became the foundation of their marketing.",
        metrics: [],
      },
      {
        sector: "despachos-profesionales",
        client: "Boutique corporate law firm · Madrid",
        anonymous: true,
        title: "From word of mouth to a full calendar",
        challenge: "Four brilliant partners, a generic website and 90% of clients coming from referrals.",
        angle: "We stopped talking about “full-service” and positioned the firm as the specialist in family-business transactions.",
        result: "Better-qualified enquiries, higher fees and the partners recognised as leaders in their niche.",
        metrics: [
          { value: "4 → 17", label: "qualified enquiries per month" },
          { value: "+32%", label: "average fee per matter" },
          { value: "9", label: "months to get there" },
        ],
      },
      {
        sector: "turismo-experiencias",
        client: "Viajes Nieva",
        anonymous: false,
        title: "Rethinking an agency at the digital crossroads",
        challenge: "An agency in a changing tourism market, facing new ways of searching for and recommending travel.",
        angle: "Strategic vision to anticipate events and redefine the role of the boutique agency.",
        result: "Key decisions for its growth as a company.",
        metrics: [],
      },
      {
        sector: "turismo-experiencias",
        client: "Cultural travel agency · Madrid",
        anonymous: true,
        title: "Travellers who book without going through portals",
        challenge: "Competing on price against giant platforms with a product nothing like theirs.",
        angle: "We made the guides the heroes and launched a newsletter with stories from every route.",
        result: "An owned community that books directly and pays for the experience, not the price.",
        metrics: [
          { value: "38%", label: "of bookings from the newsletter" },
          { value: "+24%", label: "average spend per traveller" },
          { value: "6,200", label: "subscribers in one year" },
        ],
      },
    ],
  },
  testimonials: {
    kicker: "Testimonials",
    title: "What people who've worked with us say.",
    items: [
      {
        quote:
          "In a business like ours, where things change constantly, it's very important to have someone like Nacho Latorre who can adapt to improvisation. His analysis and knowledge of social media helped us improve the brand's presence and notably grow our followers.",
        name: "Laura Franch",
        role: "Head of Communication",
        company: "Editorial Planeta",
      },
      {
        quote:
          "We writers get lost in the details, the microscopic view. To keep the literary simile, Nacho Latorre is an expert at making your story believable — in this case, your business. His analysis and advice have been a fundamental help to us.",
        name: "Germán Solís",
        role: "Deputy Director",
        company: "Escuela de Escritores",
      },
      {
        quote:
          "His strategic vision, his ability to anticipate events and his deep knowledge of marketing and the digital world helped us make decisions that have been key to our development as a company.",
        name: "Paloma Nieva",
        role: "Founding partner",
        company: "Viajes Sakai & Viajes Nieva",
      },
      {
        quote:
          "One of the best ideas we had was hiring Lateral Zinkin. We were starting our business and didn't know how to position ourselves. Nacho's ideas have become valuable marketing tools for our company.",
        name: "Margaret Hauschild",
        role: "Managing partner",
        company: "Bennet & Rey Lawyers",
      },
      {
        quote:
          "Nacho Latorre and his team did a very good job repositioning our brand. As a result we have increased sales and improved our brand image, which is exactly what we were looking for.",
        name: "Alberto Gutiérrez",
        role: "Managing director",
        company: "ElPeriódicoDeTuDía",
      },
      {
        quote:
          "Not only have we improved our sales and competitiveness, but at the most crucial moments his support and outside analysis have been key to moving our project forward.",
        name: "Francesca Murru",
        role: "Founding partner",
        company: "ComeMai",
      },
      {
        quote:
          "An efficient and effective partner that improves your vision of the business, supports your company's growth and always has smart advice available.",
        name: "Nina Morillas",
        role: "Founder and director",
        company: "Pinkus & María Wolff",
      },
      {
        quote:
          "Nacho's approach was close, personal and professional at all times. His analysis of our marketing and communication situation was spot on.",
        name: "Antonio Lence",
        role: "Managing director",
        company: "Viena Capellanes",
      },
    ],
    translated: "Translated from the original Spanish.",
  },
  founder: {
    kicker: "Who's behind it",
    name: "Nacho Latorre Tambo",
    role: "Founding partner · Consultant · Marketing lecturer",
    teaser:
      "Since 2007, Nacho has helped publishers, museums, law firms and travel agencies find their angle. Behind him, a flexible group of professionals with decades of experience.",
    bio: [
      "With a degree in Law and Business Administration from ICADE and a Master's in Sales and Marketing Management, Nacho founded Lateral Zinkin in 2007 with a simple idea: outsourced marketing could be close, professional and different.",
      "He is an expert in marketing for professional services and law firms, marketing for entrepreneurs, social media and digital transformation. He has collaborated on social media for Lonely Planet Spain and worked with brands such as Editorial Planeta, Museo Thyssen-Bornemisza and Escuela de Escritores.",
      "He combines consulting with teaching as a marketing lecturer at IMF Smart Education, training the professionals who today run marketing at many companies.",
    ],
    credentials: [
      "Law & Business · ICADE",
      "Master's in Sales and Marketing Management",
      "Marketing lecturer · IMF Smart Education",
      "Legal and professional services marketing expert",
    ],
    quote: "A consultancy's value lies in creating strategies and creativity that effectively reach our clients' clients.",
    photoAlt: "Portrait of Nacho Latorre Tambo",
    yearsLabel: "years",
    cta: "Meet Nacho",
    team: "A flexible team",
    teamDesc:
      "For each project we bring in designers, developers, copywriters and media specialists with decades of experience. Always with Nacho leading: no accounts passed from junior to junior.",
  },
  ideas: {
    kicker: "Ideas",
    title: "What we've learnt by looking sideways.",
    sub: "Real cases, our own data and signed opinions on marketing for brands with a story. No filler.",
    read: "Read article",
    minutes: "min read",
    by: "By",
    published: "Published",
    updated: "Updated",
    sources: "Sources",
    readLabel: "Reading time",
    toc: "In this article",
    sideTitle: "Is your brand as visible as it should be?",
    sideTest: "Take the test (3 min)",
    sideBook: "or book a strategy session",
    empty: "We're preparing our first articles in English. In the meantime, you can read the Spanish ones or subscribe to the newsletter.",
    back: "All ideas",
    aboutAuthor: "About the author",
    draft: "Draft: only visible in previews, not in production.",
    otherLanguages: "Also available in",
  },
  quizTeaser: {
    kicker: "Free test · 3 minutes",
    title: "How visible is your brand?",
    sub: "Eight questions to measure your brand's clarity, differentiation, visibility and conversion. You'll get a personalised diagnosis with concrete recommendations.",
    cta: "Start the test",
    bullets: ["Clarity", "Differentiation", "Visibility", "Conversion"],
  },
  newsletter: {
    kicker: "Newsletter",
    title: "Lateral ideas, once a month.",
    sub: "Cases, tools and thoughts on marketing for brands with a story. No noise. Unsubscribe anytime.",
    cta: "Subscribe on Substack",
  },
  finalCta: {
    title: "Shall we talk about your brand?",
    sub: "A 30-minute strategy session. Tell us about your project, get an honest first read, and decide whether to continue. No strings attached.",
    primary: "Book your session",
    secondary: "or message us on WhatsApp",
  },
  contact: {
    kicker: "Contact",
    title: "Let's talk about your brand.",
    sub: "Book a strategy session directly or tell us about your project and we'll reply within 24 business hours.",
    bookingTitle: "Book your strategy session",
    bookingSub: "30 minutes by video call. Free, no strings attached.",
    bookingPending: "Soon you'll be able to book here directly. In the meantime, leave your details and we'll suggest a time.",
    formTitle: "Tell us about your project",
    form: {
      name: "Name",
      email: "Email",
      company: "Company or project",
      phone: "Phone (optional)",
      sector: "Sector",
      sectorOptions: ["Culture & publishing", "Law or professional firm", "Tourism & experiences", "Other"],
      budget: "Approximate monthly budget",
      budgetOptions: ["Not sure yet", "Under €1,000", "€1,000 – 3,000", "€3,000 – 6,000", "Over €6,000"],
      message: "What do you want to achieve?",
      messagePlaceholder: "Tell us what you're working on and what you'd like to achieve.",
      consentA: "I have read and accept the",
      consentLink: "privacy policy",
      submit: "Send",
      sending: "Sending…",
      success: "Received! We'll get back to you within 24 business hours.",
      error: "We couldn't send the form. Email us directly at",
      required: "Please check the required fields.",
    },
    details: {
      phoneLabel: "Phone",
      whatsappLabel: "WhatsApp",
      whatsappText: "Message us on WhatsApp",
      emailLabel: "Email",
      addressLabel: "Studio",
    },
  },
  quiz: {
    title: "Brand visibility test",
    intro: "Answer honestly. There are no right or wrong answers: just a starting point.",
    start: "Start",
    step: "Question",
    of: "of",
    back: "Back",
    dims: {
      clarity: "Clarity",
      difference: "Differentiation",
      visibility: "Visibility",
      conversion: "Conversion",
    },
    questions: [
      {
        dim: "clarity",
        q: "When someone visits your website for the first time, do they understand within five seconds what you do and who for?",
        options: ["I don't have a website or it's outdated", "Probably not entirely", "More or less", "Yes, without a doubt"],
      },
      {
        dim: "clarity",
        q: "Have you written down your positioning and ideal client?",
        options: ["No", "It's in my head", "Yes, but we don't use it", "Yes, and it guides everything we communicate"],
      },
      {
        dim: "difference",
        q: "What sets you apart from your competitors?",
        options: ["I'm not sure", "Price", "Quality and a personal touch", "Something specific only we do"],
      },
      {
        dim: "difference",
        q: "If you removed the logos from your website and your competitors', could you tell them apart?",
        options: ["They'd be almost identical", "They'd look quite similar", "Somewhat", "We're unmistakable"],
      },
      {
        dim: "visibility",
        q: "How do most of your new clients find you?",
        options: ["Almost only word of mouth", "Social media, irregularly", "Several sources, no plan", "Search, content, press and referrals, with a plan"],
      },
      {
        dim: "visibility",
        q: "How often do you publish thoughtful content (articles, social, newsletter)?",
        options: ["Almost never", "When there's time", "Every month", "Every week, with a calendar"],
      },
      {
        dim: "conversion",
        q: "When an interested person visits your website, what happens next?",
        options: ["Nothing, there's no clear way to get in touch", "An email or a generic form", "A form, and we reply quickly", "A clear path: book, download or subscribe"],
      },
      {
        dim: "conversion",
        q: "Do you know how many enquiries you get each month and which channel they come from?",
        options: ["No idea", "A hunch", "Roughly", "Yes, we measure everything"],
      },
    ],
    gate: {
      title: "Your diagnosis is ready.",
      sub: "Leave your email to see the full report with your scores and recommendations. We'll also send it to your inbox.",
      name: "Name",
      email: "Email",
      sector: "Sector",
      consent: "I accept the privacy policy and agree to receive the diagnosis by email.",
      submit: "See my diagnosis",
      preview: "Your overall score",
    },
    results: {
      title: "Your diagnosis",
      overall: "Overall score",
      tiers: [
        {
          min: 0,
          title: "Invisible brand",
          desc: "Your brand has a lot to say, but right now the market isn't listening. The good news: this is where changes show fastest.",
        },
        {
          min: 40,
          title: "Dormant potential",
          desc: "You have solid foundations, but there are significant gaps between who you are and what the market perceives. With the right angle, the leap can be big.",
        },
        {
          min: 70,
          title: "Ready for take-off",
          desc: "Your brand is well built. The next level is sharpening differentiation and scaling what already works.",
        },
      ],
      recsTitle: "Our recommendations",
      recs: {
        clarity: "Write down who you're for and what problem you solve, and make your homepage say it in one sentence.",
        difference: "Find your angle: something only you can say. If a competitor could sign your message, you haven't found it yet.",
        visibility: "Build consistent owned channels: expert content, a newsletter and relationships with influencers. Word of mouth doesn't scale on its own.",
        conversion: "Design a clear path for every visitor: book a call, download something useful or subscribe. And measure it.",
      },
      allGood: "All four areas are in good shape. Let's talk about scaling what already works.",
      nextTitle: "What now?",
      nextSub: "We'll review your diagnosis with you in a free 30-minute strategy session.",
      bookCta: "Book a session",
      newsletterCta: "Get lateral ideas",
      retake: "Retake the test",
    },
  },
  footer: {
    claim: "Ideas & Marketing for brands with a story.",
    rights: "All rights reserved.",
    legal: { aviso: "Legal notice", privacidad: "Privacy", cookies: "Cookies" },
    explore: "Explore",
    contact: "Contact",
    follow: "Follow us",
  },
  pages: {
    services: { title: "Services", sub: "Strategy, brand and communication. Mind and hands." },
    sectors: { title: "Sectors" },
    cases: { title: "Work", sub: "Projects, challenges and results." },
    about: { title: "Nacho Latorre Tambo" },
    test: { title: "Brand visibility test", sub: "3 minutes. 8 questions. An honest diagnosis." },
    contact: { title: "Contact" },
    legalNote: "This legal text is provided in Spanish, which is the governing version.",
  },
};
